version: "3.9"

services:
  app:
    build: .
    container_name: wg-agent
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      - ggvpn-network
    ports:
      - "8050:8050"
    environment:
      - WG_AGENT_TOKEN=8FfaWRSmNrocNh93kll9IiqjvDRyuEanSQXEF2hC43s
      - LOG_PATH=logs
      - WG_INTERFACE=wg10

networks:
  ggvpn-network:
    external: true
